FROM node:11-slim

# See https://crbug.com/795759
RUN apt-get update && apt-get install -yq --no-install-recommends libgconf-2-4 && \
    rm -rf /var/lib/apt/lists/*

# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
    && apt-get install -y --no-install-recommends wget \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y --no-install-recommends google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont libxtst6 libxss1 \
       \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get purge --auto-remove -y curl \
    && rm -rf /src/*.deb \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /app
RUN groupadd -r test && useradd -r -g test -G audio,video test \
    && mkdir -p /home/test/Downloads \
    && chown -R test:test /home/test

COPY ./package.json /app/
COPY ./package-lock.json /app/
COPY ./jest-puppeteer.config.js /app
RUN chown -R test:test /app
RUN apt-get update && apt-get -y --no-install-recommends install nano && rm -rf /var/lib/apt/lists/*

USER test
WORKDIR /app
RUN npm install

ENTRYPOINT ["/usr/local/bin/npm", "--prefix", "/app", "test"]
