#!/bin/bash
# shellcheck disable=SC1091
source "$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )/pre_build"
docker-compose -f docker-compose.template.yml build --progress tty "$@"
