#!/bin/bash
DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
# shellcheck disable=SC1091
source "$DIR/pre_build"
docker-compose -f "$DIR/../build/docker-compose.build.yml" build --progress tty "$@"
