#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

docker run \
    --rm \
    -i \
    -v $DIR/../.hadolint.yaml:/root/.config/hadolint.yaml \
    hadolint/hadolint < Dockerfile || true
