#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
IMAGE=$(grep "image:" "$DIR/../docker-compose.template.yml" | sed "s/\(.*image: \)\(.*\)/\2/")
REPO=$(echo "$IMAGE" | sed "s/\(.*\):\(.*\)/\1/")
TAG=$(echo "$IMAGE" | sed "s/\(.*\):\(.*\)/\2/")

