#!/bin/bash -xe

trap "echo Exited!; exit;" SIGINT SIGTERM

function build() {
  YML=$1
  ARG=$2
  CMD="docker-compose -f $YML build $ARG"
  if ! $CMD; then
    echo "Failed: \"$CMD\""
    exit 1
  fi

  DOWN="docker-compose -f $YML down -v"
  CMD="docker-compose -f $YML up --no-build --abort-on-container-exit sut"
  if ! $CMD; then
    echo "Failed: \"$CMD\""
    $DOWN &> /dev/null || true
    exit 1
  fi
  $DOWN &> /dev/null || true
}

build docker-compose.bats.test.yml
build docker-compose.bats.custom-ssl.test.yml
build docker-compose.puppeteer.test.yml
build docker-compose.puppeteer.no-phpmyadmin.test.yml
build docker-compose.puppeteer.no-mariadb.test.yml --no-cache
